name: finances
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+5

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  fl_chart: ^0.63.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  intl: ^0.18.1
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  circular_clip_route: ^0.2.0+3
  spinner_date_time_picker: ^0.0.8
  uuid: ^4.0.0
  flutter_color_models: ^1.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"
  adaptive_icon_foreground: "assets/images/app_logo.jpg"
  adaptive_icon_background: "#ffffff"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_logo.jpg
    - assets/images/USD.png
    - assets/images/AED.png
    - assets/images/AFN.png
    - assets/images/ALL.png
    - assets/images/AMD.png
    - assets/images/ANG.png
    - assets/images/AOA.png
    - assets/images/ARS.png
    - assets/images/AUD.png
    - assets/images/AWG.png
    - assets/images/AZN.png
    - assets/images/BAM.png
    - assets/images/BBD.png
    - assets/images/BDT.png
    - assets/images/BGN.png
    - assets/images/BHD.png
    - assets/images/BIF.png
    - assets/images/BMD.png
    - assets/images/BND.png
    - assets/images/BOB.png
    - assets/images/BRL.png
    - assets/images/BSD.png
    - assets/images/BTN.png
    - assets/images/BWP.png
    - assets/images/BYN.png
    - assets/images/BZD.png
    - assets/images/CAD.png
    - assets/images/CDF.png
    - assets/images/CHF.png
    - assets/images/CLP.png
    - assets/images/CNY.png
    - assets/images/COP.png
    - assets/images/CRC.png
    - assets/images/CUP.png
    - assets/images/CVE.png
    - assets/images/CZK.png
    - assets/images/DJF.png
    - assets/images/DKK.png
    - assets/images/DOP.png
    - assets/images/DZD.png
    - assets/images/EGP.png
    - assets/images/ERN.png
    - assets/images/ETB.png
    - assets/images/EUR.png
    - assets/images/FJD.png
    - assets/images/FKP.png
    - assets/images/FOK.png
    - assets/images/GBP.png
    - assets/images/GEL.png
    - assets/images/GGP.png
    - assets/images/GHS.png
    - assets/images/GIP.png
    - assets/images/GMD.png
    - assets/images/GNF.png
    - assets/images/GTQ.png
    - assets/images/GYD.png
    - assets/images/HKD.png
    - assets/images/HNL.png
    - assets/images/HRK.png
    - assets/images/HTG.png
    - assets/images/HUF.png
    - assets/images/IDR.png
    - assets/images/ILS.png
    - assets/images/IMP.png
    - assets/images/INR.png
    - assets/images/IQD.png
    - assets/images/IRR.png
    - assets/images/ISK.png
    - assets/images/JEP.png
    - assets/images/JMD.png
    - assets/images/JOD.png
    - assets/images/JPY.png
    - assets/images/KES.png
    - assets/images/KGS.png
    - assets/images/KHR.png
    - assets/images/KID.png
    - assets/images/KMF.png
    - assets/images/KRW.png
    - assets/images/KWD.png
    - assets/images/KYD.png
    - assets/images/KZT.png
    - assets/images/LAK.png
    - assets/images/LBP.png
    - assets/images/LKR.png
    - assets/images/LRD.png
    - assets/images/LSL.png
    - assets/images/LYD.png
    - assets/images/MAD.png
    - assets/images/MDL.png
    - assets/images/MGA.png
    - assets/images/MKD.png
    - assets/images/MMK.png
    - assets/images/MNT.png
    - assets/images/MOP.png
    - assets/images/MRU.png
    - assets/images/MUR.png
    - assets/images/MVR.png
    - assets/images/MWK.png
    - assets/images/MXN.png
    - assets/images/MYR.png
    - assets/images/MZN.png
    - assets/images/NAD.png
    - assets/images/NGN.png
    - assets/images/NIO.png
    - assets/images/NOK.png
    - assets/images/NPR.png
    - assets/images/NZD.png
    - assets/images/OMR.png
    - assets/images/PAB.png
    - assets/images/PEN.png
    - assets/images/PGK.png
    - assets/images/PHP.png
    - assets/images/PKR.png
    - assets/images/PLN.png
    - assets/images/PYG.png
    - assets/images/QAR.png
    - assets/images/RON.png
    - assets/images/RSD.png
    - assets/images/RUB.png
    - assets/images/RWF.png
    - assets/images/SAR.png
    - assets/images/SBD.png
    - assets/images/SCR.png
    - assets/images/SDG.png
    - assets/images/SEK.png
    - assets/images/SGD.png
    - assets/images/SHP.png
    - assets/images/SLE.png
    - assets/images/SLL.png
    - assets/images/SOS.png
    - assets/images/SRD.png
    - assets/images/SSP.png
    - assets/images/STN.png
    - assets/images/SYP.png
    - assets/images/SZL.png
    - assets/images/THB.png
    - assets/images/TJS.png
    - assets/images/TMT.png
    - assets/images/TND.png
    - assets/images/TOP.png
    - assets/images/TRY.png
    - assets/images/TTD.png
    - assets/images/TVD.png
    - assets/images/TWD.png
    - assets/images/TZS.png
    - assets/images/UAH.png
    - assets/images/UGX.png
    - assets/images/UYU.png
    - assets/images/UZS.png
    - assets/images/VES.png
    - assets/images/VND.png
    - assets/images/VUV.png
    - assets/images/WST.png
    - assets/images/XAF.png
    - assets/images/XCD.png
    - assets/images/XDR.png
    - assets/images/XOF.png
    - assets/images/XPF.png
    - assets/images/YER.png
    - assets/images/ZAR.png
    - assets/images/ZMW.png
    - assets/images/ZWL.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
