import 'package:finances/utils/custom_icons.dart';
import 'package:finances/utils/objects.dart';
import 'package:flutter/material.dart';

import '../secondary_pages/choose_categories.dart';

String apiKey = 'b78fb11501d8e96fd8c01300';

Map currencyNames = {
  "USD": "United States Dollar",
  "AED": "United Arab Emirates Dirham",
  "AFN": "Afghan Afghani",
  "ALL": "Albanian Lek",
  "AMD": "Armenian Dram",
  "ANG": "Netherlands Antillean Guilder",
  "AOA": "Angolan Kwanza",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AWG": "Aruban Florin",
  "AZN": "Azerbaijani Manat",
  "BAM": "Bosnia-Herzegovina Convertible Mark",
  "BBD": "Barbadian Dollar",
  "BDT": "Bangladeshi Taka",
  "BGN": "Bulgarian Lev",
  "BHD": "Bahraini Dinar",
  "BIF": "Burundian Franc",
  "BMD": "Bermudan Dollar",
  "BND": "Brunei Dollar",
  "BOB": "Bolivian Boliviano",
  "BRL": "Brazilian Real",
  "BSD": "Bahamian Dollar",
  "BTN": "Bhutanese Ngultrum",
  "BWP": "Botswanan Pula",
  "BYN": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "CAD": "Canadian Dollar",
  "CDF": "Congolese Franc",
  "CHF": "Swiss Franc",
  "CLP": "Chilean Peso",
  "CNY": "Chinese Yuan",
  "COP": "Colombian Peso",
  "CRC": "Costa Rican Colón",
  "CUP": "Cuban Peso",
  "CVE": "Cape Verdean Escudo",
  "CZK": "Czech Koruna",
  "DJF": "Djiboutian Franc",
  "DKK": "Danish Krone",
  "DOP": "Dominican Peso",
  "DZD": "Algerian Dinar",
  "EGP": "Egyptian Pound",
  "ERN": "Eritrean Nakfa",
  "ETB": "Ethiopian Birr",
  "EUR": "Euro",
  "FJD": "Fijian Dollar",
  "FKP": "Falkland Islands Pound",
  "FOK": "Faroese Króna",
  "GBP": "British Pound Sterling",
  "GEL": "Georgian Lari",
  "GGP": "Guernsey Pound",
  "GHS": "Ghanaian Cedi",
  "GIP": "Gibraltar Pound",
  "GMD": "Gambian Dalasi",
  "GNF": "Guinean Franc",
  "GTQ": "Guatemalan Quetzal",
  "GYD": "Guyanaese Dollar",
  "HKD": "Hong Kong Dollar",
  "HNL": "Honduran Lempira",
  "HRK": "Croatian Kuna",
  "HTG": "Haitian Gourde",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli New Shekel",
  "IMP": "Manx pound",
  "INR": "Indian Rupee",
  "IQD": "Iraqi Dinar",
  "IRR": "Iranian Rial",
  "ISK": "Icelandic Króna",
  "JEP": "Jersey Pound",
  "JMD": "Jamaican Dollar",
  "JOD": "Jordanian Dinar",
  "JPY": "Japanese Yen",
  "KES": "Kenyan Shilling",
  "KGS": "Kyrgystani Som",
  "KHR": "Cambodian Riel",
  "KID": "Kiribati Dollar",
  "KMF": "Comorian Franc",
  "KRW": "South Korean Won",
  "KWD": "Kuwaiti Dinar",
  "KYD": "Cayman Islands Dollar",
  "KZT": "Kazakhstani Tenge",
  "LAK": "Laotian Kip",
  "LBP": "Lebanese Pound",
  "LKR": "Sri Lankan Rupee",
  "LRD": "Liberian Dollar",
  "LSL": "Lesotho Loti",
  "LYD": "Libyan Dinar",
  "MAD": "Moroccan Dirham",
  "MDL": "Moldovan Leu",
  "MGA": "Malagasy Ariary",
  "MKD": "Macedonian Denar",
  "MMK": "Myanmar Kyat",
  "MNT": "Mongolian Tugrik",
  "MOP": "Macanese Pataca",
  "MRU": "Mauritanian Ouguiya",
  "MUR": "Mauritian Rupee",
  "MVR": "Maldivian Rufiyaa",
  "MWK": "Malawian Kwacha",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "MZN": "Mozambican Metical",
  "NAD": "Namibian Dollar",
  "NGN": "Nigerian Naira",
  "NIO": "Nicaraguan Córdoba",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "OMR": "Omani Rial",
  "PAB": "Panamanian Balboa",
  "PEN": "Peruvian Sol",
  "PGK": "Papua New Guinean Kina",
  "PHP": "Philippine Peso",
  "PKR": "Pakistani Rupee",
  "PLN": "Polish Zloty",
  "PYG": "Paraguayan Guarani",
  "QAR": "Qatari Rial",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "RUB": "Russian Ruble",
  "RWF": "Rwandan Franc",
  "SAR": "Saudi Riyal",
  "SBD": "Solomon Islands Dollar",
  "SCR": "Seychellois Rupee",
  "SDG": "Sudanese Pound",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "SHP": "Saint Helena Pound",
  "SLE": "Sierra Leonean Leone",
  "SLL": "Sierra Leonean Leone",
  "SOS": "Somali Shilling",
  "SRD": "Surinamese Dollar",
  "SSP": "South Sudanese Pound",
  "STN": "São Tomé and Príncipe Dobra",
  "SYP": "Syrian Pound",
  "SZL": "Swazi Lilangeni",
  "THB": "Thai Baht",
  "TJS": "Tajikistani Somoni",
  "TMT": "Turkmenistani Manat",
  "TND": "Tunisian Dinar",
  "TOP": "Tongan Pa'anga",
  "TRY": "Turkish Lira",
  "TTD": "Trinidad and Tobago Dollar",
  "TVD": "Tuvaluan Dollar",
  "TWD": "New Taiwan Dollar",
  "TZS": "Tanzanian Shilling",
  "UAH": "Ukrainian Hryvnia",
  "UGX": "Ugandan Shilling",
  "UYU": "Uruguayan Peso",
  "UZS": "Uzbekistan Som",
  "VES": "Venezuelan Bolívar Soberano",
  "VND": "Vietnamese Dong",
  "VUV": "Vanuatu Vatu",
  "WST": "Samoan Tala",
  "XAF": "Central African CFA Franc",
  "XCD": "East Caribbean Dollar",
  "XDR": "Special Drawing Rights",
  "XOF": "West African CFA franc",
  "XPF": "CFP Franc",
  "YER": "Yemeni Rial",
  "ZAR": "South African Rand",
  "ZMW": "Zambian Kwacha",
  "ZWL": "Zimbabwean Dollar"
};

Map currencySymbols = {
  "USD": "\$",
  "EUR": "€",
  "ZWL": "\$ZW",
  "AED": "د.إ",
  "AFN": "؋",
  "ALL": "Lek",
  "AMD": "֏",
  "ANG": "ƒ",
  "AOA": "Kz",
  "ARS": "\$AR",
  "AUD": "A\$",
  "AWG": "ƒ",
  "AZN": "₼",
  "BAM": "KM",
  "BBD": "BDs\$",
  "BDT": "৳",
  "BGN": "лв",
  "BHD": ".د.ب",
  "BIF": "FBu",
  "BMD": "BD\$",
  "BND": "B\$",
  "BOB": "Bs.",
  "BRL": "R\$",
  "BSD": "BSD\$",
  "BTN": "Nu.",
  "BWP": "P",
  "BYN": "Br",
  "BZD": "BZ\$",
  "CAD": "C\$",
  "CDF": "FC",
  "CHF": "CHF",
  "CLP": "CLP\$",
  "CNY": "¥",
  "COP": "COP\$",
  "CRC": "₡",
  "CUP": "\$MN",
  "CVE": "CVE\$",
  "CZK": "Kč",
  "DJF": "Fdj",
  "DKK": "kr",
  "DOP": "RD\$",
  "DZD": "دج",
  "EGP": "£",
  "ERN": "Nfk",
  "ETB": "Br",
  "FJD": "FJD\$",
  "FKP": "£",
  "FOK": "kr",
  "GBP": "£",
  "GEL": "₾",
  "GGP": "£",
  "GHS": "₵",
  "GIP": "£",
  "GMD": "D",
  "GNF": "FG",
  "GTQ": "Q",
  "GYD": "GYD\$",
  "HKD": "HK\$",
  "HNL": "L",
  "HRK": "kn",
  "HTG": "G",
  "HUF": "Ft",
  "IDR": "Rp",
  "ILS": "₪",
  "IMP": "£",
  "INR": "₹",
  "IQD": "ع.د",
  "IRR": "﷼",
  "ISK": "kr",
  "JEP": "£",
  "JMD": "J\$",
  "JOD": "د.ا",
  "JPY": "¥",
  "KES": "KSh",
  "KGS": "сом",
  "KHR": "៛",
  "KID": "KID\$",
  "KMF": "CF",
  "KRW": "₩",
  "KWD": "د.ك",
  "KYD": "KYD\$",
  "KZT": "₸",
  "LAK": "₭",
  "LBP": "£",
  "LKR": "Rs",
  "LRD": "L\$",
  "LSL": "L",
  "LYD": "ل.د",
  "MAD": "DH",
  "MDL": "L",
  "MGA": "Ar",
  "MKD": "ден",
  "MMK": "K",
  "MNT": "₮",
  "MOP": "P",
  "MRU": "UM",
  "MUR": "₨",
  "MVR": "Rf",
  "MWK": "MK",
  "MXN": "Mex\$",
  "MYR": "RM",
  "MZN": "MT",
  "NAD": "CAD\$",
  "NGN": "₦",
  "NIO": "C\$",
  "NOK": "kr",
  "NPR": "₨",
  "NZD": "NZ\$",
  "OMR": "ر.ع.",
  "PAB": "B/.",
  "PEN": "S/.",
  "PGK": "K",
  "PHP": "₱",
  "PKR": "₨",
  "PLN": "zł",
  "PYG": "₲",
  "QAR": "ر.ق",
  "RON": "lei",
  "RSD": "дин.",
  "RUB": "₽",
  "RWF": "FRw",
  "SAR": "ر.س",
  "SBD": "SBD\$",
  "SCR": "₨",
  "SDG": "ج.س.",
  "SEK": "kr",
  "SGD": "S\$",
  "SHP": "£",
  "SLE": "Le",
  "SLL": "Le",
  "SOS": "Sh",
  "SRD": "Sr\$",
  "SSP": "£",
  "STN": "Db",
  "SYP": "£",
  "SZL": "L",
  "THB": "฿",
  "TJS": "SM",
  "TMT": "m",
  "TND": "د.ت",
  "TOP": "T\$",
  "TRY": "₺",
  "TTD": "TTD\$",
  "TVD": "TVD\$",
  "TWD": "NT\$",
  "TZS": "TSh",
  "UAH": "₴",
  "UGX": "USh",
  "UYU": "\$U",
  "UZS": "so'm",
  "VES": "Bs.",
  "VND": "₫",
  "VUV": "VT",
  "WST": "T",
  "XAF": "FCFA",
  "XCD": "EC\$",
  "XDR": "SDR",
  "XOF": "CFA",
  "XPF": "₣",
  "YER": "﷼",
  "ZAR": "R",
  "ZMW": "ZK",
};

class Data {
  static List<Currency> currenciesList = [];
}

List<Category> categories = [
  Category(
    name: "Food and drinks",
    iconData: CustomIcons.food,
    color: Colors.orange,
  ),
  Category(
    name: "Shopping",
    iconData: Icons.shopping_bag_outlined,
    color: Colors.blue,
  ),
  Category(
    name: "Housing",
    iconData: Icons.house,
    color: Colors.red,
  ),
  Category(
    name: "Transportation",
    iconData: Icons.train,
    color: Colors.grey,
  ),
  Category(
    name: "Vehicle",
    iconData: CustomIcons.car,
    color: Color.fromARGB(255, 5, 82, 171),
  ),
  Category(
    name: "Life and entertainement",
    iconData: Icons.family_restroom,
    color: Colors.green,
  ),
  Category(
    name: "Communication and internet",
    iconData: Icons.computer,
    color: Colors.purple,
  ),
  Category(
    name: "Financial expanses",
    iconData: Icons.attach_money_outlined,
    color: Colors.pink,
  ),
  Category(
    name: "Investments",
    iconData: Icons.trending_up,
    color: Color.fromARGB(255, 12, 202, 180),
  ),
  Category(
    name: "Income",
    iconData: CustomIcons.money_1,
    color: Color.fromARGB(255, 249, 192, 21),
  ),
  Category(
    name: "Others",
    iconData: Icons.menu,
    color: Color.fromARGB(255, 87, 87, 87),
  ),
];

List<SubCategory> subcategories = [
  SubCategory(
    name: "General",
    iconData: categories[0].iconData,
    color: categories[0].color,
    category: categories[0],
  ),
  SubCategory(
    name: "Bar and Cafe",
    iconData: Icons.coffee,
    color: categories[0].color,
    category: categories[0],
  ),
  SubCategory(
    name: "Groceries",
    iconData: Icons.local_grocery_store,
    color: categories[0].color,
    category: categories[0],
  ),
  SubCategory(
    name: "Restaurant and fast-foods",
    iconData: Icons.fastfood,
    color: categories[0].color,
    category: categories[0],
  ),
  SubCategory(
    name: "General",
    iconData: categories[1].iconData,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Clothes and shoes",
    iconData: CustomIcons.tshirt,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Drug store and chemist",
    iconData: CustomIcons.pump_soap,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Electronics and accessories",
    iconData: CustomIcons.phone_iphone,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Free time",
    iconData: CustomIcons.child,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Gifts and joy",
    iconData: CustomIcons.gift,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Health and beauty",
    iconData: CustomIcons.spa,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Home and garden",
    iconData: Icons.grass,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Jewels and accessories",
    iconData: Icons.diamond,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Kids",
    iconData: Icons.stroller,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Pets and animals",
    iconData: Icons.pets,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "Stationery and tools",
    iconData: CustomIcons.tools,
    color: categories[1].color,
    category: categories[1],
  ),
  SubCategory(
    name: "General",
    iconData: categories[2].iconData,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Energy and utilities",
    iconData: Icons.lightbulb,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Maintenance and repairs",
    iconData: CustomIcons.wrench,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Mortgage",
    iconData: CustomIcons.account_balance,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Proprety insurance",
    iconData: CustomIcons.house_damage,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Rent",
    iconData: CustomIcons.key,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "Services",
    iconData: CustomIcons.local_laundry_service,
    color: categories[2].color,
    category: categories[2],
  ),
  SubCategory(
    name: "General",
    iconData: categories[3].iconData,
    color: categories[3].color,
    category: categories[3],
  ),
  SubCategory(
    name: "Business trip",
    iconData: Icons.business_center,
    color: categories[3].color,
    category: categories[3],
  ),
  SubCategory(
    name: "Long distance",
    iconData: Icons.flight,
    color: categories[3].color,
    category: categories[3],
  ),
  SubCategory(
    name: "Public transport",
    iconData: CustomIcons.directions_bus,
    color: categories[3].color,
    category: categories[3],
  ),
  SubCategory(
    name: "Taxi",
    iconData: Icons.local_taxi_outlined,
    color: categories[3].color,
    category: categories[3],
  ),
  SubCategory(
    name: "General",
    iconData: categories[4].iconData,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Fuel",
    iconData: CustomIcons.fuel,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Leasing",
    iconData: CustomIcons.coins,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Parking",
    iconData: CustomIcons.parking,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Rentals",
    iconData: CustomIcons.key,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Vehicle insurance",
    iconData: CustomIcons.id_card,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "Vehicle maintenance",
    iconData: CustomIcons.wrench,
    color: categories[4].color,
    category: categories[4],
  ),
  SubCategory(
    name: "General",
    iconData: categories[5].iconData,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Active sport and fitness",
    iconData: CustomIcons.dumbbell,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Alcohol and tobacco",
    iconData: CustomIcons.wine_bottle,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Books, audio and subscriptions",
    iconData: CustomIcons.book,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Charity and gifts",
    iconData: CustomIcons.gift,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Culture and sports",
    iconData: CustomIcons.hands_helping,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Education and developpement",
    iconData: CustomIcons.graduation_cap,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Health care and doctor",
    iconData: CustomIcons.healing,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Hobbies",
    iconData: CustomIcons.heart,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Holiday, trips and hotels",
    iconData: CustomIcons.palm_tree,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Life events",
    iconData: CustomIcons.birthday,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Lottery and gambling",
    iconData: CustomIcons.dice,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "TV and streaming",
    iconData: CustomIcons.live_tv,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "Wellness and beauty",
    iconData: CustomIcons.flowers,
    color: categories[5].color,
    category: categories[5],
  ),
  SubCategory(
    name: "General",
    iconData: categories[6].iconData,
    color: categories[6].color,
    category: categories[6],
  ),
  SubCategory(
    name: "Internet",
    iconData: CustomIcons.wifi,
    color: categories[6].color,
    category: categories[6],
  ),
  SubCategory(
    name: "Phone and cell phone",
    iconData: CustomIcons.phone,
    color: categories[6].color,
    category: categories[6],
  ),
  SubCategory(
    name: "Postal services",
    iconData: CustomIcons.mail,
    color: categories[6].color,
    category: categories[6],
  ),
  SubCategory(
    name: "Software, apps and games",
    iconData: CustomIcons.gamepad,
    color: categories[6].color,
    category: categories[6],
  ),
  SubCategory(
    name: "General",
    iconData: categories[7].iconData,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Advisory",
    iconData: CustomIcons.chat,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Charges and fees",
    iconData: CustomIcons.percent,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Child support",
    iconData: CustomIcons.baby,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Fines",
    iconData: CustomIcons.police,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Insurances",
    iconData: CustomIcons.id_card,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Loan and interest",
    iconData: CustomIcons.ticket,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "Taxes",
    iconData: CustomIcons.money,
    color: categories[7].color,
    category: categories[7],
  ),
  SubCategory(
    name: "General",
    iconData: categories[8].iconData,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "Collections",
    iconData: CustomIcons.collections_bookmark,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "Financial investments",
    iconData: CustomIcons.coins,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "Realty",
    iconData: Icons.house_outlined,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "Savings",
    iconData: CustomIcons.money,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "Vehicles and chattelts",
    iconData: CustomIcons.cab,
    color: categories[8].color,
    category: categories[8],
  ),
  SubCategory(
    name: "General",
    iconData: categories[9].iconData,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Checks and cupons",
    iconData: CustomIcons.money_check,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Child support",
    iconData: CustomIcons.baby,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Dues and grant",
    iconData: CustomIcons.verified,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Gifts",
    iconData: CustomIcons.gift,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Interest and dividends",
    iconData: CustomIcons.percent,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Lending and renting",
    iconData: CustomIcons.coins,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Lottery and gambling",
    iconData: CustomIcons.dice,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Refunds (tax, purshase)",
    iconData: CustomIcons.loop_alt,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Rental income",
    iconData: Icons.house,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Sale",
    iconData: CustomIcons.money_bill_alt,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "Wage and invoices",
    iconData: CustomIcons.file_invoice_dollar,
    color: categories[9].color,
    category: categories[9],
  ),
  SubCategory(
    name: "General",
    iconData: categories[10].iconData,
    color: categories[10].color,
    category: categories[10],
  ),
  SubCategory(
    name: "Missing",
    iconData: Icons.question_mark,
    color: categories[10].color,
    category: categories[10],
  ),
  SubCategory(
    name: "Stolen",
    iconData: Icons.cancel,
    color: categories[10].color,
    category: categories[10],
  ),
];
